Switched database source, major refactor

diff --git a/cal-events b/cal-events
--- a/cal-events
+++ b/cal-events
@@ -1,25 +1,25 @@
-#!/usr/bin/env sh
+#!/bin/sh
 #
 # Author: Pooya Moradi
-# Date : 1401-01-22
+# Date : 2022/04/11 | 1401-01-22
 # License: MIT
 #
 # Description: A simple script to fetch Iranian and international calendar
 #              events
 #
-# Dependencies: jq curl date jdate
+# Dependencies: jq curl date jdate idate awk grep cut
 
 # TODO
-# - convert date above and prepend the result to it
-# - find a better database
 
 show_help() {
     cat << EOF
-cal-events: shows Iranian/international calendar events for current day
+cal-events: shows Iranian/international calendar events for current day or
+            future days
 
 Usage: cal-events [OPTIONS]
 Options:
     -s      Sync database json by downloading files from internet
+    -d      Number of days into future from today (including today)
     -V      Print script version
     -h      Display the help message
 
@@ -28,6 +28,8 @@ Examples:
     cal-events -s
     # get events for current day
     cal-events
+    # get events for today, tomorrow, and the day after tomorrow
+    cal-events -d3
 EOF
 }
 
@@ -74,57 +76,59 @@ sync() {
     log info "Syncing database to $data_dir"
     mkdir --parents "$data_dir"
 
-    if ! fetch "$jalali_link" "$jalali"; then
-        log error "Problem in downloading $jalali_link"
+    if ! fetch "$db_link" "$events"; then
+        log error "Problem in downloading $db_link"
         return 1
     fi
 
-    if ! fetch "$gregorian_link" "$gregorian"; then
-        log error "Problem in downloading $gregorian_link"
-        return 1
-    fi
     _db_files=$(printf '%s\n' "$data_dir/"*)
     log info "Downloaded files: $_db_files"
     log info "Done syncing"
 }
 
-get_iranian() {
-    read -r month day << END
-$(jdate '+%m %d' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")")
-END
-    if ! jq --raw-output --argjson m "$month" --argjson d "$day" \
-        '.events | map (select(.month == $m and .day == $d)) [] | .title.fa_IR' \
-        "$jalali"; then
-        log error "Filtering $jalali failed"
-        exit 1
-    fi
+get_month_day() {
+    case "$1" in
+        "Persian Calendar")
+            jdate '+%m %d' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")"
+            ;;
+        "Hijri Calendar")
+            idate --gregorian "$(date '+%Y%m%d' -d "+$offset days")" \
+                | grep Output \
+                | grep -o '[0-9]\+/[[:space:]]*[0-9]\+/[0-9]\+' \
+                | awk -F/ '{print $2, $1}'
+            ;;
+        "Gregorian Calendar")
+            date '+%m %d' -d "+$offset days"
+            ;;
+    esac
 }
 
-get_hijri() {
-    :
-}
-
-get_gregorian() {
+get_event() {
+    _cal="$1"
     read -r month day << END
-$(date '+%m %d' -d "+$offset days")
+$(get_month_day "$_cal")
 END
-    if ! jq --raw-output --argjson m "$month" --argjson d "$day" \
-        '.events | map (select(.month == $m and .day == $d)) [] | .title.fa_IR' \
-        "$gregorian"; then
-        log error "Filtering $gregorian failed"
+
+    if ! jq --raw-output \
+        --arg cal "$_cal" \
+        --argjson m "$month" --argjson d "$day" \
+        '.[$cal] | map (select(.month == $m and .day == $d and
+                              (.type == "Iran" or .type == "International"))) []
+                 as $m
+                 | (if $m.holiday
+                    then ($m.title + " (تعطیل)")
+                    else $m.title end)' \
+        "$events"; then
+        log error "Filtering $events failed"
         exit 1
     fi
-
 }
 
 # global variables
-version=0.2
+version=0.4
 data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/cal-events"
-jalali="$data_dir/jalali.json"
-gregorian="$data_dir/gregorian.json"
-db_link_base="https://github.com/persiancal/cal-events/raw/refs/heads/gh-pages"
-jalali_link="$db_link_base/jalali.json"
-gregorian_link="$db_link_base/gregorian.json"
+events="$data_dir/events.json"
+db_link="https://github.com/persian-calendar/persian-calendar/raw/refs/heads/main/PersianCalendar/data/events.json"
 days=1
 offset=0
 
@@ -132,6 +136,7 @@ while getopts sVhd: opt; do
     case $opt in
         h)
             show_help
+            exit
             ;;
         s)
             sync
@@ -142,6 +147,7 @@ while getopts sVhd: opt; do
             ;;
         V)
             printf "%s\n" "$version"
+            exit
             ;;
         *)
             log error "Bad usage! Check help (-h)"
@@ -156,17 +162,18 @@ if [ -n "$1" ]; then
     exit 2
 fi
 
-check_deps jq curl jdate date
+check_deps jq curl jdate idate date
 
-# check if db json files exist
-if [ ! -f "$jalali" ] || [ ! -f "$gregorian" ]; then
+# check if db json file exists
+if [ ! -f "$events" ]; then
     log error "Database not found. Sync first (-s)"
     exit 1
 fi
 
 if [ "$days" -eq 1 ]; then
-    get_iranian
-    get_gregorian
+    get_event "Persian Calendar"
+    get_event "Hijri Calendar"
+    get_event "Gregorian Calendar"
     exit
 fi
 
@@ -174,10 +181,12 @@ while [ "$days" -gt 0 ]; do
     week_day=$(jdate '+%G' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")")
     month_day=$(jdate '+%W' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")" | cut -d/ -f3)
     printf "«%s, %s»\n" "$week_day" "$month_day"
-    get_iranian
-    get_gregorian
+
+    get_event "Persian Calendar"
+    get_event "Hijri Calendar"
+    get_event "Gregorian Calendar"
+
     days=$((days - 1))
     offset=$((offset + 1))
     printf "——————————————\n"
 done
-
