Add -d switch for offset days

diff --git a/cal-events b/cal-events
--- a/cal-events
+++ b/cal-events
@@ -88,6 +88,35 @@ sync() {
     log info "Done syncing"
 }
 
+get_iranian() {
+    read -r month day << END
+$(jdate '+%m %d' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")")
+END
+    if ! jq --raw-output --argjson m "$month" --argjson d "$day" \
+        '.events | map (select(.month == $m and .day == $d)) [] | .title.fa_IR' \
+        "$jalali"; then
+        log error "Filtering $jalali failed"
+        exit 1
+    fi
+}
+
+get_hijri() {
+    :
+}
+
+get_gregorian() {
+    read -r month day << END
+$(date '+%m %d' -d "+$offset days")
+END
+    if ! jq --raw-output --argjson m "$month" --argjson d "$day" \
+        '.events | map (select(.month == $m and .day == $d)) [] | .title.fa_IR' \
+        "$gregorian"; then
+        log error "Filtering $gregorian failed"
+        exit 1
+    fi
+
+}
+
 # global variables
 version=0.2
 data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/cal-events"
@@ -96,8 +125,10 @@ gregorian="$data_dir/gregorian.json"
 db_link_base="https://github.com/persiancal/cal-events/raw/refs/heads/gh-pages"
 jalali_link="$db_link_base/jalali.json"
 gregorian_link="$db_link_base/gregorian.json"
+days=1
+offset=0
 
-while getopts sVh opt; do
+while getopts sVhd: opt; do
     case $opt in
         h)
             show_help
@@ -105,6 +136,9 @@ while getopts sVh opt; do
         s)
             sync
             exit "$?"
+            ;;
+        d)
+            days="$OPTARG"
             ;;
         V)
             printf "%s\n" "$version"
@@ -130,22 +164,20 @@ if [ ! -f "$jalali" ] || [ ! -f "$gregorian" ]; then
     exit 1
 fi
 
-read -r month day << END
-$(jdate '+%m %d')
-END
-if ! jq --raw-output --argjson m "$month" --argjson d "$day" \
-    '.events | map (select(.month == $m and .day == $d)) [] | .title.fa_IR' \
-    "$jalali"; then
-    log error "Filtering $jalali failed"
-    exit 1
+if [ "$days" -eq 1 ]; then
+    get_iranian
+    get_gregorian
+    exit
 fi
 
-read -r month day << END
-$(date '+%m %d')
-END
-if ! jq --raw-output --argjson m "$month" --argjson d "$day" \
-    '.events | map (select(.month == $m and .day == $d)) [] | .title.fa_IR' \
-    "$gregorian"; then
-    log error "Filtering $gregorian failed"
-    exit 1
-fi
+while [ "$days" -gt 0 ]; do
+    week_day=$(jdate '+%G' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")")
+    month_day=$(jdate '+%W' --jalali "$(date '+%Y/%m/%d' -d "+$offset days")" | cut -d/ -f3)
+    printf "«%s, %s»\n" "$week_day" "$month_day"
+    get_iranian
+    get_gregorian
+    days=$((days - 1))
+    offset=$((offset + 1))
+    printf "——————————————\n"
+done
+
